### ISSUE TITLE
an issues

### ISSUE THREAD

**Issue by PeakYuQ** [RITCHIEHuang/DeepRL_Algorithms#11]
when i run (python DeepRL_Algorithms-master/Algorithms/pytorch/DDPG/main.py)  has a problem that tips 'No module named 'Common.fixed_size_replay_memory'', then i really not found this .py file? could you tell me what happend? than you.

**Comment by RITCHIEHuang** [comment]
> when i run (python DeepRL_Algorithms-master/Algorithms/pytorch/DDPG/main.py) has a problem that tips 'No module named 'Common.fixed_size_replay_memory'', then i really not found this .py file? could you tell me what happend? than you.

Sorry for that bug, I've merged Common.fixed_size_replay_memory to Common.replay_memory before, the DDPG code was not updated accordingly, you can check for the latest code.
