### ISSUE TITLE
too slow when using SAC and SAC_Alpha

### ISSUE THREAD

**Issue by R-Ceph** [RITCHIEHuang/DeepRL_Algorithms#12]
Compared with the PPO algorithm (10000 fps for BipedalWalker-v2 ), the running speed of the Sac algorithm series (100 fps for BipedalWalker-v2) is much slower. I test it in both Linux (12 CPU cores and no GPU) and wsl2 in win10 (i9-10700 and no GPU ).

At first, I thought it was caused by the unequal dimensions of the two tensors( line 23 in sac_step.py,  q_value_1 and target_next_value, line 27 in sac_alpha_step, q_value_1, target_q_value ), but it was still very slow after modification.

**Comment by RITCHIEHuang** [comment]
> Compared with the PPO algorithm (10000 fps for BipedalWalker-v2 ), the running speed of the Sac algorithm series (100 fps for BipedalWalker-v2) is much slower. I test it in both Linux (12 CPU cores and no GPU) and wsl2 in win10 (i9-10700 and no GPU ).
> 
> At first, I thought it was caused by the unequal dimensions of the two tensors( line 23 in sac_step.py, q_value_1 and target_next_value, line 27 in sac_alpha_step, q_value_1, target_q_value ), but it was still very slow after modification.

Yeah, the implemented `SAC` algorithm should be slower than `PPO` especially when you compare their sampling process,  `PPO` is on-policy and `SAC` is off-policy, I implemented multi-process sampling for `PPO` but not for the `SAC`, you can speed up `SAC` focus on accelerating the sampling process in an asynchronous way.

**Comment by R-Ceph** [comment]
The off-policy algorithm is indeed slower than the on-policy, but it seems unacceptable to be 100 times slower LoL... I will check where the key problems are when I have spare time.
