### ISSUE TITLE
shape of PPO advantages

### ISSUE THREAD

**Issue by R-Ceph** [RITCHIEHuang/DeepRL_Algorithms#13]
The shape of output advantages of the estimate_advantages function in GAE.py is (batch_size, 1), but the importance ratio in the ppo_step function is (batch_size, ), which will have a certain impact on the convergence speed of the algorithm as the shape of suurr1 and surr2 is (batch_size, batch_size).

Only a small change is required:
> surr1 = ratio * advantages.reshape(-1)

Result in Gridword before:
> Iter: 1, num steps: 4000, total reward: -178.9500, min reward: -12.0000, max reward:  5.9500, average reward: -3.1955, sample time:  0.3478
> Iter: 2, num steps: 4000, total reward: -128.9500, min reward: -16.0000, max reward:  5.6000, average reward: -2.3027, sample time:  0.2542
> Iter: 3, num steps: 4000, total reward: -44.6000, min reward: -10.0000, max reward:  7.5500, average reward: -0.7690, sample time:  0.2599
> Iter: 4, num steps: 4000, total reward:  60.2000, min reward: -9.0000, max reward:  6.7000, average reward:  0.8853, sample time:  0.2566
> Iter: 5, num steps: 4000, total reward:  172.0000, min reward: -8.0000, max reward:  7.3000, average reward:  2.1235, sample time:  0.2605
> Iter: 6, num steps: 4000, total reward:  232.6500, min reward: -9.0000, max reward:  7.3000, average reward:  2.6140, sample time:  0.2673
> Iter: 7, num steps: 4000, total reward:  314.7000, min reward: -10.0000, max reward:  8.4500, average reward:  2.9971, sample time:  0.2619
> Iter: 8, num steps: 4000, total reward:  291.3500, min reward: -7.0000, max reward:  6.9000, average reward:  2.5116, sample time:  0.2615
> Iter: 9, num steps: 4000, total reward:  394.7500, min reward: -10.0000, max reward:  7.6000, average reward:  3.1083, sample time:  0.2657
> Iter: 10, num steps: 4000, total reward:  432.3500, min reward: -10.0000, max reward:  7.8500, average reward:  3.1104, sample time:  0.2624

Results after:
> Iter: 1, num steps: 4000, total reward: -173.5000, min reward: -15.0000, max reward:  6.3500, average reward: -2.7540, sample time:  0.3204
> Iter: 2, num steps: 4000, total reward:  77.4000, min reward: -8.0000, max reward:  8.1500, average reward:  1.0320, sample time:  0.2714
> Iter: 3, num steps: 4000, total reward:  585.7500, min reward: -8.8000, max reward:  7.4000, average reward:  3.6609, sample time:  0.2593
> Iter: 4, num steps: 4000, total reward:  574.3000, min reward: -7.0000, max reward:  8.5500, average reward:  3.6119, sample time:  0.2592
> Iter: 5, num steps: 4000, total reward:  1946.3500, min reward: -1.1500, max reward:  8.6500, average reward:  4.5264, sample time:  0.2648
> Iter: 6, num steps: 4000, total reward:  3432.3500, min reward:  0.9500, max reward:  11.5000, average reward:  4.9816, sample time:  0.2682
> Iter: 7, num steps: 4000, total reward:  4349.9500, min reward: -0.1000, max reward:  8.6500, average reward:  4.9319, sample time:  0.2734
> Iter: 8, num steps: 4000, total reward:  4214.1000, min reward:  1.8000, max reward:  9.0500, average reward:  4.8718, sample time:  0.3343
> Iter: 9, num steps: 4000, total reward:  4549.7000, min reward:  0.6500, max reward:  12.4500, average reward:  5.0721, sample time:  0.2909
> Iter: 10, num steps: 4000, total reward:  4280.2500, min reward:  1.7000, max reward:  8.6500, average reward:  5.0475, sample time:  0.2748

**Comment by RITCHIEHuang** [comment]
@han-x Nice Thanks for pointing out the bug : )
