### ISSUE TITLE
A visitor's opinion

### ISSUE THREAD

**Issue by LaplaceJack** [RITCHIEHuang/DeepRL_Algorithms#2]
Warining: Your pictures in the Markdown were missing.

**Comment by RITCHIEHuang** [comment]
> Warining: Your pictures in the Markdown were missing.

Is there something wrong with your internet ? It seems ok in my browser.

**Comment by LaplaceJack** [comment]
Oh yeah you're right. It turns out that my internet is not so skr.

**Comment by RITCHIEHuang** [comment]
Skr, hhhh  : ). I'll close the issue.
