### ISSUE TITLE
some question about the result figure.

### ISSUE THREAD

**Issue by DeruiLiu** [RITCHIEHuang/DeepRL_Algorithms#3]
Excuse me, your result figures are very beautiful!!  Can you tell me how can I plot the figure like yours ?  the code in your plt_utils cannot show shadows like yours.

**Comment by RITCHIEHuang** [comment]
The shadow draws the deviation of rewards, that means you need to run the same experiment multiple times, then, you’ll get the shadow plots. You may refer the document of Seaborn library : )

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
