### ISSUE TITLE
RuntimeError in TRPO

### ISSUE THREAD

**Issue by pytorchinfo** [RITCHIEHuang/DeepRL_Algorithms#4]
Thanks for providing the wonderful repo! It helps.

Unforunately, when I ran `./Algorithms/pytorch/TRPO/main.py`, I got the following error:

Could you please give some suggestions? Thanks in advanced.

```
D:\Programs\anaconda3\envs\pytorch17\lib\site-packages\gym\logger.py:30: UserWarning: WARN: Box bound precision lowered by casting to float32
  warnings.warn(colorize('%s: %s'%('WARN', msg % args), 'yellow'))
Iter: 1, num steps: 4000, total reward: -3180.0536, min reward: -126.2744, max reward: -3.1223, average reward: -106.0018, sample timD:\  25.8737
Traceback (most recent call last):
  File "main.py", line 47, in <module>
    main()
  File "D:\Programs\anaconda3\envs\pytorch17\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "D:\Programs\anaconda3\envs\pytorch17\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "D:\Programs\anaconda3\envs\pytorch17\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "D:\Programs\anaconda3\envs\pytorch17\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "main.py", line 35, in main
    trpo.learn(writer, i_iter)
  File "D:\DeepRL_Algorithms-master\Algorithms\pytorch\TRPO\trpo.py", line 134, in learn
    trpo_step(self.policy_net, self.value_net, batch_state, batch_action,
  File "D:\DeepRL_Algorithms-master\Algorithms\pytorch\TRPO\trpo_step.py", line 77, in trpo_step
    update_policy(policy_net, states, actions, old_log_probs, advantages, max_kl, damping)
  File "D:\DeepRL_Algorithms-master\Algorithms\pytorch\TRPO\trpo_step.py", line 173, in update_policy
    step_dir = conjugate_gradient(Hvp, loss_grad)  # approximation solution of H^(-1)g
  File "D:\DeepRL_Algorithms-master\Algorithms\pytorch\TRPO\trpo_step.py", line 94, in conjugate_gradient
    Hvp = Hvp_f(p)  # A @ p
  File "D:\DeepRL_Algorithms-master\Algorithms\pytorch\TRPO\trpo_step.py", line 152, in Hvp
    kl = policy_net.get_kl(states)
  File "D:\DeepRL_Algorithms-master\Algorithms\pytorch\Models\Policy.py", line 79, in get_kl
    mean = self.policy(x)
  File "D:\Programs\anaconda3\envs\pytorch17\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "D:\Programs\anaconda3\envs\pytorch17\lib\site-packages\torch\nn\modules\linear.py", line 93, in forward
    return F.linear(input, self.weight, self.bias)
  File "D:\Programs\anaconda3\envs\pytorch17\lib\site-packages\torch\nn\functional.py", line 1690, in linear
    ret = torch.addmm(bias, input, weight.t())
RuntimeError: mat1 and mat2 shapes cannot be multiplied (4000x24 and 128x4)
```

BTW, I encountered similar errors when I tried to run SAC alpha `/Algorithms/pytorch/SAC_Alpha/main.py`

```
D:\Programs\anaconda3\envs\pytorch17\lib\site-packages\gym\logger.py:30: UserWarning: WARN: Box bound precision lowered by casting to float32
  warnings.warn(colorize('%s: %s'%('WARN', msg % args), 'yellow'))
Traceback (most recent call last):
  File "sac_alpha_main.py", line 69, in <module>
    main()
  File "D:\Programs\anaconda3\envs\pytorch17\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "D:\Programs\anaconda3\envs\pytorch17\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "D:\Programs\anaconda3\envs\pytorch17\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "D:\Programs\anaconda3\envs\pytorch17\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "sac_alpha_main.py", line 57, in main
    sac_alpha.learn(writer, i_iter)
  File "D:\DeepRL_Algorithms-master\DeepRL_Algorithms-master\Algorithms\pytorch\SAC_Alpha\sac_alpha.py", line 160, in learn
    self.update(batch, k)
  File "D:\DeepRL_Algorithms-master\DeepRL_Algorithms-master\Algorithms\pytorch\SAC_Alpha\sac_alpha.py", line 203, in update
    sac_alpha_step(self.policy_net, self.q_net_1, self.q_net_2, self.alpha, self.q_net_target_1,
  File "D:\DeepRL_Algorithms-master\DeepRL_Algorithms-master\Algorithms\pytorch\SAC_Alpha\sac_alpha_step.py", line 18, in sac_alpha_step
    next_actions, next_log_probs = policy_net.rsample(next_states)
  File "D:\DeepRL_Algorithms-master\DeepRL_Algorithms-master\Algorithms\pytorch\Models\Policy.py", line 69, in rsample
    log_prob -= (torch.log(1. - action.pow(2) + eps)).sum(dim=-1)
RuntimeError: The size of tensor a (4) must match the size of tensor b (256) at non-singleton dimension 1

```

**Comment by RITCHIEHuang** [comment]
> 
> 
> Thanks for providing the wonderful repo! It helps.
> 
> Unforunately, when I ran `./Algorithms/pytorch/TRPO/main.py`, I got the following error:
> 
> Could you please give some suggestions? Thanks in advanced.
> 
> ```
> D:\Programs\anaconda3\envs\pytorch17\lib\site-packages\gym\logger.py:30: UserWarning: WARN: Box bound precision lowered by casting to float32
>   warnings.warn(colorize('%s: %s'%('WARN', msg % args), 'yellow'))
> Iter: 1, num steps: 4000, total reward: -3180.0536, min reward: -126.2744, max reward: -3.1223, average reward: -106.0018, sample timD:\  25.8737
> Traceback (most recent call last):
>   File "main.py", line 47, in <module>
>     main()
>   File "D:\Programs\anaconda3\envs\pytorch17\lib\site-packages\click\core.py", line 829, in __call__
>     return self.main(*args, **kwargs)
>   File "D:\Programs\anaconda3\envs\pytorch17\lib\site-packages\click\core.py", line 782, in main
>     rv = self.invoke(ctx)
>   File "D:\Programs\anaconda3\envs\pytorch17\lib\site-packages\click\core.py", line 1066, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "D:\Programs\anaconda3\envs\pytorch17\lib\site-packages\click\core.py", line 610, in invoke
>     return callback(*args, **kwargs)
>   File "main.py", line 35, in main
>     trpo.learn(writer, i_iter)
>   File "D:\DeepRL_Algorithms-master\Algorithms\pytorch\TRPO\trpo.py", line 134, in learn
>     trpo_step(self.policy_net, self.value_net, batch_state, batch_action,
>   File "D:\DeepRL_Algorithms-master\Algorithms\pytorch\TRPO\trpo_step.py", line 77, in trpo_step
>     update_policy(policy_net, states, actions, old_log_probs, advantages, max_kl, damping)
>   File "D:\DeepRL_Algorithms-master\Algorithms\pytorch\TRPO\trpo_step.py", line 173, in update_policy
>     step_dir = conjugate_gradient(Hvp, loss_grad)  # approximation solution of H^(-1)g
>   File "D:\DeepRL_Algorithms-master\Algorithms\pytorch\TRPO\trpo_step.py", line 94, in conjugate_gradient
>     Hvp = Hvp_f(p)  # A @ p
>   File "D:\DeepRL_Algorithms-master\Algorithms\pytorch\TRPO\trpo_step.py", line 152, in Hvp
>     kl = policy_net.get_kl(states)
>   File "D:\DeepRL_Algorithms-master\Algorithms\pytorch\Models\Policy.py", line 79, in get_kl
>     mean = self.policy(x)
>   File "D:\Programs\anaconda3\envs\pytorch17\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
>     result = self.forward(*input, **kwargs)
>   File "D:\Programs\anaconda3\envs\pytorch17\lib\site-packages\torch\nn\modules\linear.py", line 93, in forward
>     return F.linear(input, self.weight, self.bias)
>   File "D:\Programs\anaconda3\envs\pytorch17\lib\site-packages\torch\nn\functional.py", line 1690, in linear
>     ret = torch.addmm(bias, input, weight.t())
> RuntimeError: mat1 and mat2 shapes cannot be multiplied (4000x24 and 128x4)
> ```
> 
> BTW, I encountered similar errors when I tried to run SAC alpha `/Algorithms/pytorch/SAC_Alpha/main.py`
> 
> ```
> D:\Programs\anaconda3\envs\pytorch17\lib\site-packages\gym\logger.py:30: UserWarning: WARN: Box bound precision lowered by casting to float32
>   warnings.warn(colorize('%s: %s'%('WARN', msg % args), 'yellow'))
> Traceback (most recent call last):
>   File "sac_alpha_main.py", line 69, in <module>
>     main()
>   File "D:\Programs\anaconda3\envs\pytorch17\lib\site-packages\click\core.py", line 829, in __call__
>     return self.main(*args, **kwargs)
>   File "D:\Programs\anaconda3\envs\pytorch17\lib\site-packages\click\core.py", line 782, in main
>     rv = self.invoke(ctx)
>   File "D:\Programs\anaconda3\envs\pytorch17\lib\site-packages\click\core.py", line 1066, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "D:\Programs\anaconda3\envs\pytorch17\lib\site-packages\click\core.py", line 610, in invoke
>     return callback(*args, **kwargs)
>   File "sac_alpha_main.py", line 57, in main
>     sac_alpha.learn(writer, i_iter)
>   File "D:\DeepRL_Algorithms-master\DeepRL_Algorithms-master\Algorithms\pytorch\SAC_Alpha\sac_alpha.py", line 160, in learn
>     self.update(batch, k)
>   File "D:\DeepRL_Algorithms-master\DeepRL_Algorithms-master\Algorithms\pytorch\SAC_Alpha\sac_alpha.py", line 203, in update
>     sac_alpha_step(self.policy_net, self.q_net_1, self.q_net_2, self.alpha, self.q_net_target_1,
>   File "D:\DeepRL_Algorithms-master\DeepRL_Algorithms-master\Algorithms\pytorch\SAC_Alpha\sac_alpha_step.py", line 18, in sac_alpha_step
>     next_actions, next_log_probs = policy_net.rsample(next_states)
>   File "D:\DeepRL_Algorithms-master\DeepRL_Algorithms-master\Algorithms\pytorch\Models\Policy.py", line 69, in rsample
>     log_prob -= (torch.log(1. - action.pow(2) + eps)).sum(dim=-1)
> RuntimeError: The size of tensor a (4) must match the size of tensor b (256) at non-singleton dimension 1
> ```

Quite sorry for that, there's some bugs in that version of code, I'll update my code and you can try this again.

**Comment by RITCHIEHuang** [comment]
Welcome for any issues, I'll close then.

**Comment by pytorchinfo** [comment]
Thank you for your prompt reply. I am looking forward to your updates.
